$(document).ready(start);

const cards = [
    { suit: "Eichel", rank: "Sieben" },
    { suit: "Eichel", rank: "Acht" },
    { suit: "Eichel", rank: "Neun" },
    { suit: "Eichel", rank: "Unter" },
    { suit: "Eichel", rank: "Ober" },
    { suit: "Eichel", rank: "König" },
    { suit: "Eichel", rank: "Zehn" },
    { suit: "Eichel", rank: "Ass" },
    { suit: "Blatt", rank: "Sieben" },
    { suit: "Blatt", rank: "Acht" },
    { suit: "Blatt", rank: "Neun" },
    { suit: "Blatt", rank: "Unter" },
    { suit: "Blatt", rank: "Ober" },
    { suit: "Blatt", rank: "König" },
    { suit: "Blatt", rank: "Zehn" },
    { suit: "Blatt", rank: "Ass" },
    { suit: "Herz", rank: "Sieben" },
    { suit: "Herz", rank: "Acht" },
    { suit: "Herz", rank: "Neun" },
    { suit: "Herz", rank: "Unter" },
    { suit: "Herz", rank: "Ober" },
    { suit: "Herz", rank: "König" },
    { suit: "Herz", rank: "Zehn" },
    { suit: "Herz", rank: "Ass" },
    { suit: "Schelln", rank: "Sieben" },
    { suit: "Schelln", rank: "Acht" },
    { suit: "Schelln", rank: "Neun" },
    { suit: "Schelln", rank: "Unter" },
    { suit: "Schelln", rank: "Ober" },
    { suit: "Schelln", rank: "König" },
    { suit: "Schelln", rank: "Zehn" },
    { suit: "Schelln", rank: "Ass" },
  ];
  